### ISSUE TITLE
Finalize poster schema

### ISSUE THREAD

**Issue by dekanbro** [bitbeckers/moloch-safe-modules#9]
add a way to do reactions by people on allow list (like thumbs up and thumbs down)

**Comment by dekanbro** [comment]
schema
```{
controller: string;
target: string;
type: string;
description: string;
link: string;
}```


space deliminator

**reason:**
tag: CookieJar <_uid>
content: <json schema>

**reaction**
tag: CookieJar.reaction
content: <_uid>  <DOWN/UP>  <msg.sender>

**Comment by bitbeckers** [comment]
### Model
#### Summon cookie jar

emits:   
```solidity
SummonCookieJar(address(_cookieJar), details, _initializer, uid);
```

`uid`:
```solidity
bytes32 uid = bytes32ToString(keccak256(abi.encodePacked(address(cookieJar), chainId)));
```

`details`:

```json
{
  "type":"Baal",
  "name":"Moloch Pastries",
  "description":"This is where you add some more content",
  "link":"app.daohaus.club/0x64/0x0....666"
}
 ```

#### Reach in Jar

emits:
```solidity
    GiveCookie(cookieMonster, amount, fee, uid);
    IPoster(POSTER_ADDR).post(_reason, tag));
```

`tag`:
`string.concat(POSTER_TAG, " ", uid))`


### TODO

- [ ] Set UID on contract init (`string`)
- [ ] Emit UID during summon event
- [ ] Add UID to `GiveCookie` event
- [ ]
